import AppKit
import Foundation

// MARK: - Installed Model

struct InstalledModel {
    let path: String
    let filename: String
    let size: Int64
    var isActive: Bool { path == ModelManager.shared.activeModelPath() }
}

// MARK: - Model Manager

final class ModelManager {
    static let shared = ModelManager()

    let modelsDir = NSHomeDirectory() + "/models"

    private static func pythonVersion() -> String {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        let pipe = Pipe()
        task.standardOutput = pipe
        try? task.run()
        task.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let ver = String(data: data, encoding: .utf8) ?? ""
        let parts = ver.split(separator: ".")
        if parts.count >= 2 { return "\(parts[0]).\(parts[1])" }
        return "3.11"
    }

    func activeModelPath() -> String {
        guard let content = try? String(contentsOfFile: CONFIG_PATH, encoding: .utf8) else { return "" }
        for line in content.components(separatedBy: .newlines) {
            let parts = line.split(separator: "=", maxSplits: 1).map { $0.trimmingCharacters(in: .whitespaces) }
            if parts.count == 2 && parts[0] == "MODEL_PATH" {
                return parts[1].replacingOccurrences(of: "\"", with: "")
            }
        }
        return ""
    }

    // MARK: Installed list

    func listInstalled() -> [InstalledModel] {
        let fm = FileManager.default
        guard let items = try? fm.contentsOfDirectory(atPath: modelsDir) else { return [] }
        return items.filter { $0.hasSuffix(".gguf") }.map { name in
            let path = modelsDir + "/" + name
            let size = (try? fm.attributesOfItem(atPath: path)[.size] as? Int64) ?? 0
            return InstalledModel(path: path, filename: name, size: size)
        }.sorted { $0.filename < $1.filename }.map { m in
            InstalledModel(path: m.path, filename: m.filename, size: m.size)
        }
    }

    // MARK: Delete

    func deleteModel(at path: String) throws {
        try FileManager.default.removeItem(atPath: path)
    }

    // MARK: Activate

    func activateModel(at path: String, label: String? = nil, repo: String? = nil) throws {
        let filename = (path as NSString).lastPathComponent
        let resolvedLabel = label ?? filename
        let resolvedRepo = repo ?? filename
        try writeServerConfig(modelPath: path, file: filename, label: resolvedLabel, repo: resolvedRepo)
        ServerManager.shared.reloadConfigAndRestart()
    }

    private func writeServerConfig(modelPath: String, file: String, label: String, repo: String) throws {
        guard let content = try? String(contentsOfFile: CONFIG_PATH, encoding: .utf8) else {
            throw NSError(domain: "ModelManager", code: 1, userInfo: [NSLocalizedDescriptionKey: "server.conf not found. Run install first."])
        }
        var port = "8080"
        var context = "8192"
        var host = "0.0.0.0"
        for line in content.components(separatedBy: .newlines) {
            let parts = line.split(separator: "=", maxSplits: 1).map { $0.trimmingCharacters(in: .whitespaces) }
            guard parts.count == 2 else { continue }
            switch parts[0] {
            case "PORT":    port = parts[1]
            case "CONTEXT": context = parts[1]
            case "HOST":    host = parts[1].replacingOccurrences(of: "\"", with: "")
            default: break
            }
        }
        let newContent = """
        # llama.cpp — generated by llama-menubar
        MODEL_LABEL="\(label)"
        MODEL_REPO="\(repo)"
        MODEL_FILE="\(file)"
        MODEL_PATH="\(modelPath)"
        PORT=\(port)
        CONTEXT=\(context)
        HOST="\(host)"
        """
        try FileManager.default.createDirectory(atPath: (CONFIG_PATH as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
        try newContent.write(toFile: CONFIG_PATH, atomically: true, encoding: .utf8)
    }

    // MARK: Download

    /// Spawns `python3 -m huggingface_hub download <repo> <filename> --local-dir <modelsDir>`
    /// Streams stdout/stderr to logCallback, parses percentage into progressCallback.
    /// Returns the Process so the caller can cancel.
    @discardableResult
    func downloadModel(
        repo: String,
        file: String,
        logCallback: @escaping (String) -> Void,
        progressCallback: @escaping (Double) -> Void
    ) -> Process {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        task.arguments = ["-m", "huggingface_hub", "download", repo, file, "--local-dir", modelsDir]
        var env = ProcessInfo.processInfo.environment
        env["DYLD_LIBRARY_PATH"] = NSHomeDirectory() + "/.local/lib"
        if let hfToken = UserDefaults.standard.string(forKey: "hf_token"), !hfToken.isEmpty {
            env["HF_TOKEN"] = hfToken
        }
        task.environment = env

        let outPipe = Pipe()
        let errPipe = Pipe()
        task.standardOutput = outPipe
        task.standardError = errPipe

        let percentRegex = try? NSRegularExpression(pattern: "(\\d{1,3})%\\|", options: [])

        outPipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            guard !data.isEmpty, let s = String(data: data, encoding: .utf8) else { return }
            DispatchQueue.main.async { logCallback(s) }
            if let regex = percentRegex {
                let range = NSRange(s.startIndex..<s.endIndex, in: s)
                if let m = regex.firstMatch(in: s, options: [], range: range),
                   let r = Range(m.range(at: 1), in: s), let pct = Double(s[r]) {
                    DispatchQueue.main.async { progressCallback(pct / 100.0) }
                }
            }
        }
        errPipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            guard !data.isEmpty, let s = String(data: data, encoding: .utf8) else { return }
            DispatchQueue.main.async { logCallback(s) }
        }

        do {
            try task.run()
        } catch {
            DispatchQueue.main.async { logCallback("\nFailed to start download: \(error.localizedDescription)\n") }
        }
        return task
    }
}