import AppKit
import Foundation

// MARK: - Server Config

struct ServerConfig {
    var modelLabel = ""
    var modelRepo = ""
    var modelFile = ""
    var modelPath = ""
    var port = "8080"
    var context = "8192"
    var host = "0.0.0.0"
    var ngl = "40"
    var fa = "1"
    var ctk = "q8_0"
    var ctv = "q8_0"
    var threads = "0"
    var batchSize = "512"
    var profile = "balanced"

    static let defaultKeys: [(key: String, value: KeyPath<ServerConfig, String>)] = [
        ("PORT", \.port),
        ("CONTEXT", \.context),
        ("HOST", \.host),
        ("NGL", \.ngl),
        ("FA", \.fa),
        ("CTK", \.ctk),
        ("CTV", \.ctv),
        ("THREADS", \.threads),
        ("BATCH_SIZE", \.batchSize),
        ("PROFILE", \.profile),
        ("MODEL_LABEL", \.modelLabel),
        ("MODEL_REPO", \.modelRepo),
        ("MODEL_FILE", \.modelFile),
        ("MODEL_PATH", \.modelPath),
    ]
}

// MARK: - Config Manager

final class ConfigManager {
    static let shared = ConfigManager()

    private let configPath = "\(NSHomeDirectory())/.config/llama/server.conf"
    private let startScriptPath = "\(NSHomeDirectory())/.local/bin/llama-server-start.sh"

    // MARK: Read

    func read() -> ServerConfig {
        var config = ServerConfig()
        guard let content = try? String(contentsOfFile: configPath, encoding: .utf8) else { return config }
        for line in content.components(separatedBy: .newlines) {
            let parts = line.split(separator: "=", maxSplits: 1).map { $0.trimmingCharacters(in: .whitespaces) }
            guard parts.count == 2 else { continue }
            let raw = parts[1].replacingOccurrences(of: "\"", with: "")
            switch parts[0] {
            case "PORT":        config.port = raw
            case "CONTEXT":     config.context = raw
            case "HOST":        config.host = raw
            case "NGL":         config.ngl = raw
            case "FA":          config.fa = raw
            case "CTK":         config.ctk = raw
            case "CTV":         config.ctv = raw
            case "THREADS":     config.threads = raw
            case "BATCH_SIZE":  config.batchSize = raw
            case "PROFILE":     config.profile = raw
            case "MODEL_LABEL": config.modelLabel = raw
            case "MODEL_REPO":  config.modelRepo = raw
            case "MODEL_FILE":  config.modelFile = raw
            case "MODEL_PATH":  config.modelPath = raw
            default: break
            }
        }
        return config
    }

    // MARK: Write server.conf

    func write(_ config: ServerConfig) throws {
        let content = """
        # llama.cpp — generated by LlamaMate
        MODEL_LABEL="\(config.modelLabel)"
        MODEL_REPO="\(config.modelRepo)"
        MODEL_FILE="\(config.modelFile)"
        MODEL_PATH="\(config.modelPath)"
        PORT=\(config.port)
        CONTEXT=\(config.context)
        HOST="\(config.host)"
        NGL=\(config.ngl)
        FA=\(config.fa)
        CTK="\(config.ctk)"
        CTV="\(config.ctv)"
        THREADS=\(config.threads)
        BATCH_SIZE=\(config.batchSize)
        PROFILE="\(config.profile)"
        """
        try FileManager.default.createDirectory(atPath: (configPath as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
        try content.write(toFile: configPath, atomically: true, encoding: .utf8)
        try writeStartScript()
    }

    // MARK: Apply changes (write + reload + restart)

    func apply(_ config: ServerConfig) throws {
        try write(config)
        ServerManager.shared.reloadConfigAndRestart()
    }

    // MARK: Start script

    func writeStartScript() throws {
        try FileManager.default.createDirectory(atPath: (startScriptPath as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
        let script = """
        #!/usr/bin/env bash
        set -euo pipefail
        CONFIG="${HOME}/.config/llama/server.conf"
        [[ -f "$CONFIG" ]] && source "$CONFIG"

        TOTAL_RAM=$(sysctl -n hw.memsize 2>/dev/null || echo 0)
        MODEL_SIZE=$(stat -f%z "${MODEL_PATH:-/dev/null}" 2>/dev/null || echo 0)
        CTX_RAM=$(( MODEL_SIZE / 3 ))
        NEEDED=$(( MODEL_SIZE + CTX_RAM ))
        if [ "$TOTAL_RAM" -gt 0 ] && [ "$NEEDED" -gt "$TOTAL_RAM" ]; then
          NEEDED_GB=$(( NEEDED / 1073741824 ))
          TOTAL_GB=$(( TOTAL_RAM / 1073741824 ))
          echo "[LlamaMate] WARNING: Model needs ~${NEEDED_GB} GB RAM but system has ${TOTAL_GB} GB." >&2
          echo "[LlamaMate] The server may be killed by macOS memory pressure." >&2
        fi

        export PATH="${HOME}/.local/bin:${PATH}"
        export DYLD_LIBRARY_PATH="${HOME}/.local/lib:${DYLD_LIBRARY_PATH:-}"
        exec "${HOME}/.local/bin/llama-server" \\
          -m "${MODEL_PATH}" \\
          -c "${CONTEXT}" \\
          --port "${PORT}" \\
          --host "${HOST}" \\
          -ngl "${NGL:-40}" \\
          -fa "${FA:-0}" \\
          -ctk "${CTK:-f16}" \\
          -ctv "${CTV:-f16}" \\
          -t "${THREADS:-0}" \\
          -b "${BATCH_SIZE:-512}"
        """
        try script.write(toFile: startScriptPath, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: startScriptPath)
    }

    // MARK: Paths (read-only access)

    var configFilePath: String { configPath }
    var startScriptFilePath: String { startScriptPath }
}
